name: Release BetterBook plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        id: get_tag
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create release
        id: create_release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          file: build/libs/BetterBook.jar
          release_name: Release ${{ github.ref }}
          body: |
            #### Release ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false
